CAMUNDA_REST_ADDRESS=https://[REGION].zeebe.camunda.io/[CLUSTER-ID]
CAMUNDA_GRPC_ADDRESS=https://[CLUSTER-ID].[REGION].zeebe.camunda.io:443
CAMUNDA_TOKEN_AUDIENCE=zeebe.camunda.io
camunda-auth.server.url=https://login.cloud.camunda.io/oauth/token
camunda.client.auth.client-id=
camunda.client.auth.client-secret=
camunda.client.cloud.cluster-id=
camunda.client.cloud.region=
